# Deployment file for product 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-product-prd
  labels:
    app: i27-product-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-product-prd
  template:
    metadata:
      labels:
        app: i27-product-prd
    spec:
      containers:
      - name: i27-product-prd
        image: DIT # Image tag will be replaced by shared library
---
apiVersion: v1
kind: Service
metadata:
  name: i27-product-prd
  labels:
    app: i27-product-prd
spec:
  type: NodePort
  ports:
  - port: 8132
    targetPort: 8132
  selector:
    app: i27-product-prd 